// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class LocationResult;

@interface LocationResult : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithLatitude:(NSNumber *)latitude
    longitude:(NSNumber *)longitude;
@property(nonatomic, strong) NSNumber * latitude;
@property(nonatomic, strong) NSNumber * longitude;
@end

/// The codec used by LocationApi.
NSObject<FlutterMessageCodec> *LocationApiGetCodec(void);

@protocol LocationApi
- (void)getCurrentLocationWithCompletion:(void(^)(LocationResult *_Nullable, FlutterError *_Nullable))completion;
@end

extern void LocationApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<LocationApi> *_Nullable api);

NS_ASSUME_NONNULL_END
